### ISSUE TITLE
Release a new version with sheetBackgroundColor support

### ISSUE THREAD

**Issue by vitherain** [kcotias/react-native-gesture-bottom-sheet#17]
Hello,

please let me ask when you plan to release a new version supporting a new prop `sheetBackgroundColor` adde in [this PR](https://github.com/kcotias/react-native-gesture-bottom-sheet/pull/14)? We are currently in situation when we really need it. :-) 

Thanks!

**Comment by kcotias** [comment]
Hey man! I'm planning to do this today! Have been stuck in job, almost zero time haha

**Comment by kcotias** [comment]
Hey @vitherain, just released a new version! Check it out :)

**Comment by vitherain** [comment]
Great! Thanks @kcotias!
