### ISSUE TITLE
Animated: `useNativeDriver` was not specified.

### ISSUE THREAD

**Issue by bamoha** [kcotias/react-native-gesture-bottom-sheet#20]
Hello, 

I get this when trying to use the library, what can I do?

```Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
at node_modules/react-native/Libraries/Animated/src/NativeAnimatedHelper.js:284:4 in shouldUseNativeDriver
at node_modules/react-native/Libraries/Animated/src/animations/SpringAnimation.js:106:49 in constructor
at node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:154:26 in start
at node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:160:13 in start
at node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:374:10 in animations.forEach$argument_0
at [native code]:null in forEach
at node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:356:6 in result.start
at http://192.168.0.139:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:285147:22 in onPanResponderRelease
at node_modules/react-native/Libraries/Interaction/PanResponder.js:572:12 in clearInteractionHandle
at node_modules/react-native/Libraries/Interaction/PanResponder.js:490:30 in panHandlers.onResponderRelease
at [native code]:null in forEach
at [native code]:null in callFunctionReturnFlushedQueue```

This is what I did, but didnt work.

` <BottomSheet useNativeDriver={false} hasDraggableIcon ref={bottomSheet} height={600} />
`

**Comment by cheerswisdom** [comment]
Same issue for me. 
Error: "Animated: `useNativeDriver` was not specified"

**Comment by coucoseth** [comment]
me too

**Comment by abenmoussa** [comment]
me too, i have the issue

**Comment by vj-abishek** [comment]
How to fix this?

**Comment by kcotias** [comment]
Hey guys, sorry for the delay, I was busy with work these months. I just merged a PR that solves this issue, will be releasing a new version of the package right now! Just update your pkg version and the warning should be gone :)
