### ISSUE TITLE
Close function is not working

### ISSUE THREAD

**Issue by deargosep** [kcotias/react-native-gesture-bottom-sheet#21]
when trying ref.current.close() it throws an error

`this.setModalVisible is not a function. (In 'this.setModalVisible(false)', 'this.setModalVisible' is undefined)`

**Comment by coucoseth** [comment]
was this solved?
how do I close the bottom sheet after I navigate to another page or without swiping

**Comment by kcotias** [comment]
Just checked here and bottomSheet.current.close(); works as expected! Need further help?

**Comment by deargosep** [comment]
Thanks, it appeared it was an issue with my own code
