### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by luis-antonio-ac** [kcotias/react-native-gesture-bottom-sheet#26]
When i run
`yarn add @types/react-native-gesture-bottom-sheet -D`

I get:
`error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2freact-native-gesture-bottom-sheet: Not found".`

**Comment by adujoseph** [comment]
facing thesame issue

**Comment by kcotias** [comment]
unfortunately, this pkg isn't typed yet :/
